apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  jwt: ODAzYTg1YjQ2YjUyMmUzOTQ1MjJhNTY2ZjhlMDZkMmU4ZTUzYjVlNTk1MDc3ZmU0MWQ5OTljNDI5ODRkMDg0NzAzZWVmYTUyMWQxODZhMTY2N2U3ZTg3ZTY0YmJjYjlhOTQ0ZjE0MzdjYjVmMjcxZTJmMmRhZjIwOGE0YjkzZDk2YmJjZDY3YWE1ZjY2NjY0NzQwM2YwYmVkNWJmZDNkYWVlNjYyOTc1N2ViN2NmMzg1ZDMwYmZjNjQ4NjkzZmM1MTk3N2RmNjBiMzM0NjgxNWM3NjcyMWVmM2NmOTE1NWZiZTlkNWZiNjMyYTc2ZTVjNDY4YTZhYjExNDk3MDFhYmZiYmI1MzIxNGFlYTZhMjJiZmNjODI3MGM1NzJkYjAyNjQ4ZTc5NjlmMDcwNWU1ZjA0MzM1MDI1OTg4NGU4M2U5MDgxNjBiNDdiZGQyN2I5OTZhYjI4OTVkNjAyM2FiZjMxNzBkYzA2ODI3NGJjNTVjYWQ2OGEzNzJiYmQzZDNiYmE4NDhiMDBkNmM3Y2M1NmEyYWEwYTc2OWIyNGY1MTljMTg3Y2E2NjE1OTUxMGJiNTUzZjM2Y2Q1YTcxMGUxNjVkZjdmNGI4MTg4M2ZiZDk5OGRmMTVjZTRjMTEzZjdmOTU2NWExOTNjNWM2NTZkZWM4NDJjY2I2YzkwNTE1YTQK
